# Generated by Django 5.1.6 on 2025-05-12 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_loyalty_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_line1',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid UK postcode.', regex='^[A-Z]{1,2}\\d[A-Z\\d]? ?\\d[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid UK phone number starting with 07 or +44.', regex='^(\\+44\\s?7\\d{3}|\\(?07\\d{3}\\)?)\\s?\\d{3}\\s?\\d{3}$')]),
        ),
    ]
