# Generated by Django 5.1.6 on 2025-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('Oily', 'Oily'), ('Dry', 'Dry'), ('Combination', 'Combination'), ('Sensitive', 'Sensitive'), ('Normal', 'Normal')], max_length=20, null=True),
        ),
    ]
