# Generated by Django 5.1.6 on 2025-05-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
