# Generated by Django 5.1.6 on 2025-05-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='image',
        ),
    ]
