# Generated by Django 5.1.6 on 2025-02-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20250228_1030'),
    ]

    operations = [
    ]
