# Generated by Django 5.1.6 on 2025-03-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_skintype_product_skin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skin_type',
        ),
        migrations.AddField(
            model_name='product',
            name='skin_types',
            field=models.ManyToManyField(blank=True, to='products.skintype'),
        ),
    ]
